language: java
jdk:
- oraclejdk8
script:
- "./mnvw package"
env:
  matrix:
    secure: XfmCjffJkLeQVoHpfDFo/D3j+SXXPPTQtxCLXFas5uz+AgkmAkOjw8wVCAFlHSS8X60q3uy6hqNUlVhsFsNqwOnf3uOsAs9zpBkEGFcAnV2vKQf5+c+X+TAF2l+ynIwUnnKF8uMENJ4pifOa6MxeRiQgjwnKyVtx8FiJYktdY4SJzoPZXdRxv/1ga/jHJCGTuOJn3Yb2eW+KGEgZDcOC32e6rxQOHqZ1Q3xz+umvxe3CCUbhFyP9yNbVUdQWy9ifFpB4HTM7dzgMZr6sZvCR75JezjKVGUmHTJ/JvFr6cTRXpvNBmzmU21VsJX1eAuWyTN16UPxF5k0aLp4DKDEmV25eO4uo/27BJKAqPRe4w1bU59YSsvp2xK50TPDUyqdxXvVvzeAc4ZQSoLINFEnbMSIB3gGx3VozG3oJnP4LM3ACjkL25pJ+KHReYU2bEk4RyyMtXrrqXrSvv3w3KhGepjGNRgIR45b+fQ1hFP7p3U0QBRmoz1xkOly2AWiuS5cpIZL4YGCnMl3dkljFXr7EUXBTo5GgnhOXwzwonGGG8rKdf9XOs3qBM8s8oC7I0n5YwlG82DbMluo405W3FSqeOG0XlZKlb/JjgUy5wWdTcUHCoVEvKeYxjbLv0cBkdUqRdGrC62a81TdV3Uorl/x8+UGbPbYToQdFHizhnENPpew=
